### ISSUE TITLE
Fisher information matrix

### ISSUE THREAD

**Issue by ismailsenoz** [biaslab/ExponentialFamily.jl#35]
Distributions.jl is not exporting Fisher information. If we know the analytic forms of Fisher matrices, adding those for speed purposes in methods that can be utilized in other packages would be beneficial.

**Comment by bvdmitri** [comment]
We need fisher information matrix for the InverseGamma as well. Could someone of you @Nimrais or @ismailsenoz derive it please?

**Comment by Nimrais** [comment]
@bvdmitri I can take it, I have some stuff to finish this week I can do it at Tuesday.

**Comment by bvdmitri** [comment]
@Nimrais 
This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/1) for tracking and prioritization.

**Comment by bvdmitri** [comment]
ping @Nimrais

**Comment by Nimrais** [comment]
@bvdmitri I see only InverseGamma is not assigned. We are talking about it?

**Comment by bvdmitri** [comment]
@Nimrais  Please read two messages above

**Comment by Nimrais** [comment]
@bvdmitri https://github.com/biaslab/ExponentialFamily.jl/pull/141

**Comment by bvdmitri** [comment]
Well done guys! I will close the issue, Contingency is not done, but it can be a separate issue if needed.
